### ISSUE TITLE
Keybinding in i3wm

### ISSUE THREAD

**Issue by edthedev** [cknadler/vim-anywhere#39]
In case there's any interest in including documentation for configuring the key binding in other window managers, here's how to set up the key-binding in i3wm.

Add the following line to `~/.i3/config`:

`bindsym $mod+Alt+v exec ~/.vim-anywhere/bin/run`

Remember to reload i3wm, for the new configuration to take effect. This is bound to `$mod+shift+r`, by default.

If interested in including this information, feel free to assign this ticket to me, and I can submit a patch to the README.

**Comment by cknadler** [comment]
Yeah, feel free to submit a patch! Thanks for the interest. ^_^

Resolving.

**Comment by edthedev** [comment]
Cool. I sent a pull request. Least I can do by way of thanks.
Great tool. Thanks!

**Comment by cknadler** [comment]
Damn. It takes me __a year and a half__ to reply and you have a PR up in 15 minutes. Props dude, you're amazing. :beers:
