### ISSUE TITLE
How to change a file name and use :Gist

### ISSUE THREAD

**Issue by shinokada** [cknadler/vim-anywhere#40]
I used to `:sav ~/path/to/filename.rb` and then `:Gist` to upload it to githubgist. But it does not change the file name and used doc-140503064838.

Is there anyway I can change the file name?

Thanks in advance.

**Comment by cknadler** [comment]
I'm not sure why this is happening. `:sav` should open the new saved file. Which Gist plugin are you using?

**Comment by cknadler** [comment]
Resolving. Feel free to reopen if you're still having this issue and I'll be glad to help. Thanks!
