### ISSUE TITLE
After saving and close a paragraph of text, break lines are not copied.

### ISSUE THREAD

**Issue by AikChun** [cknadler/vim-anywhere#41]
I wrote a short two-paragraph text on vim-anywhere which I saved and closed and was ready to paste it on my blog post. The resulting view was an conjoined wall of text.

P.S: I love your work. vim-anywhere is indispensable for me now!

**Comment by cknadler** [comment]
This works fine for me on OSX. Can you still get this to repro? If so, let me know the details (OS, source text) so I can figure it out.

Thanks!

**Comment by cknadler** [comment]
Can you reproduce this issue? I'll resolve this for now, but if you can get it to repro, feel free to reopen. Thanks!
