### ISSUE TITLE
Text not getting to the clipboard in Ubuntu Gnome 14.04

### ISSUE THREAD

**Issue by forbajato** [cknadler/vim-anywhere#42]
Just installed and updated in Ubuntu Gnome 14.04, I have gvim installed and am running the clipboard manager Parcellite. 

When writing in vim-anywhere everything works well.  When I write and exit the /tmp/vim-anywhere directory is updated but the text is not seen on the clipboard and is not available for pasting.

When using vim-anywhere in the past (with Ubuntu 13.10 and KDE) it worked well with Parcellite.  Now I can't seem to get the text from vim-anywhere onto the clipboard.  Any thoughts?

**Comment by cknadler** [comment]
Interesting. I'm not familiar with Parcellite. Is this still an issue? If so, let me know and I'll take a look. If you happen to figure it out, I'd happily accept a pull request.

Thanks!

**Comment by cknadler** [comment]
Closing due to lack of response. Feel free to reopen if you're still having this issue.
