### ISSUE TITLE
Am I missing something, but what's the point?

### ISSUE THREAD

**Issue by 097115** [cknadler/vim-anywhere#48]
Sorry, I probably miss something very obvious but anyway:

1. vim-anywhere doesn't get the "original" text from the source input (like quoted email), you have to do this manually (like copying there and pasting in vim;
2. it also doesn't pastes the resulting text, just copies it to clipboard, and once again, you have to paste it manually.

So, that's the point then? :) Sure, I can assign a system-wide hotkey to open a new Vim buffer, paste there anything I want, edit, copy to clipboard, and paste the anywhere I want. vim-anywhere seems to save me just one keypress, am I wrong?

**Comment by cknadler** [comment]
> Once invoked, vim-anywhere will open a buffer. Close it and it's contents are copied to your clipboard and your previous application is refocused.

Thats pretty much what it does. For me, this saves me more than a single keystroke.

Just `hotkey -> write -> :wq` to have opened a vim buffer and copied it's contents into your clipboard automatically. I'm not sure of a faster way, but then again, if you are, feel free to open an issue with details.

As far as automatically copying original text and pasting result text, I've thought about adding these as configurable options, but they currently aren't implemented. If you have a good idea on how to implement either of these, I'd gladly accept a pull request.

Thanks.

**Comment by thiswillbeyourgithub** [comment]
@cknadler 3 years later :p 
Why not adding an option like "if the saved file has **p\*** as its last character then paste it automatically, otherwise let the app work like before" ?
\* on an otherwise empty line
So basically your file could look like this :
`code
bash things
blablabli
p`
