### ISSUE TITLE
Umlaut problems

### ISSUE THREAD

**Issue by habi** [cknadler/vim-anywhere#49]
The copy-paste process b0rks Umlauts.

When I use `vim-anywhere` to write some text (see [this short screencast](http://cl.ly/ZpGZ)) the umlauts are not returning correctly from the buffer.
On pasting I get `√§` for ä, `√∂` for ö and `√º` for ü.
In the corresponding file in `/tmp/vim-anywhere` the characters are saved correctly...

OS X "10.10.2 (14C109)", MacVim "Custom Version 7.4 (73)" installed via `brew install macvim` and `vim-anywhere` installed immediately after reading about it on [one thing well](http://onethingwell.org/post/110899397989/vim-anywhere).

**Comment by cknadler** [comment]
Hey, thanks for bringing this up. Marking this as a bug.

I think this is probably related to #23. I'll see if I can't figure out why it's getting copied incorrectly.

**Comment by cknadler** [comment]
Fixed!

**Comment by habi** [comment]
Thanks!
