### ISSUE TITLE
Getting Python crash when opening [OS X]

### ISSUE THREAD

**Issue by rdlugosz** [cknadler/vim-anywhere#53]
See [this gist](https://gist.github.com/rdlugosz/40f658e521af3e2e720a) for the crash log... Fresh install, relatively [recent build of MacVim](https://gist.github.com/rdlugosz/f517dba6c952ec65c3c3).

**Comment by cknadler** [comment]
Hmn, are you sure this is related to vim-anywhere? Nothing in the project references anything in Python as far as I can tell.

**Comment by rdlugosz** [comment]
Will investigate further and update if I can reproduce without any of my
local config. I don't have any other crashing issues with macvim outside of
when it's launched via vim-anywhere, so there's something going on
somewhere.

**Comment by rdlugosz** [comment]
So it looks like the crash is related to the [YouCompleteMe](https://github.com/Valloric/YouCompleteMe) Plugin; when I have the plugin commented out of my vimrc I do not see the crashes. I was able to add a guard around the line that loads the YCM plugin that seems to have fixed my problem:

```
if match(argv(0), "vim-anywhere") == -1
  Plugin 'valloric/youcompleteme'
endif
```

No idea why YCM crashes when MacVim is started via vim-anywhere and not when I run `mvim` from the terminal...
