### ISSUE TITLE
Can't use in Mail

### ISSUE THREAD

**Issue by AdamSLevy** [cknadler/vim-anywhere#54]
When I try to use vim-anywhere in the Mail app on OS X 10.11 El Capitan, I get an error dialog saying

"The action “Run Shell Script” encountered an error."

Let me know if you need more information.

**Comment by cknadler** [comment]
Hmn, I just gave it a shot and it worked fine for me. Is this still happening to you?

**Comment by cknadler** [comment]
Resolving. Let me know if you can get this to repro.
