### ISSUE TITLE
is it just copy and paste for linux, how did you solve that?

### ISSUE THREAD

**Issue by jlopezfisica** [cknadler/vim-anywhere#59]
I am not using bash shell is it a problem? I can start vim by going to the folder and using ./run. however I can not set up the keybinding

**Comment by jlopezfisica** [comment]
@cknadler can you help me man

**Comment by jlopezfisica** [comment]
@cknadler oke everything is working however I need to press ctrl-v to paste the text on my email. it doesnot go directly when saving. In addition, it does not respect the spaces between lines

**Comment by cknadler** [comment]
Vim-anywhere doesn't auto paste. I mention this in the readme. There was an old version that did, but it caused more issues for people than just pasting manually.
