### ISSUE TITLE
Breaks Ubuntu 17.10

### ISSUE THREAD

**Issue by basile-henry** [cknadler/vim-anywhere#60]
As soon as the install script is executed my current session crashes and when I try to login it crashes again. I have a pretty much fresh install of Ubuntu 17.10 so hopefully it's not just some weird setup of mine that produced the error.

Here is a relevant excerpt from `/var/log/syslog`:

```
Nov 14 23:20:49 coffee gnome-session[6082]: gnome-session-binary[6082]: WARNING: App 'org.gnome.SettingsDaemon.MediaKeys.desktop' respawning too quickly
Nov 14 23:20:49 coffee gnome-session-binary[6082]: WARNING: App 'org.gnome.SettingsDaemon.MediaKeys.desktop' respawning too quickly
Nov 14 23:20:49 coffee gnome-session-binary[6082]: Unrecoverable failure in required component org.gnome.SettingsDaemon.MediaKeys.desktop
Nov 14 23:20:49 coffee gnome-session[6082]: gnome-session-binary[6082]: CRITICAL: We failed, but the fail whale is dead. Sorry....
Nov 14 23:20:49 coffee gnome-session-binary[6082]: CRITICAL: We failed, but the fail whale is dead. Sorry....
Nov 14 23:20:49 coffee org.a11y.atspi.Registry[1301]: XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
Nov 14 23:20:49 coffee org.a11y.atspi.Registry[1301]:       after 21 requests (21 known processed) with 0 events remaining.
Nov 14 23:20:49 coffee kernel: [ 2291.925365] rfkill: input handler enabled
Nov 14 23:20:49 coffee gdm3: GdmDisplay: display lasted 2.453852 seconds
Nov 14 23:20:49 coffee nautilus[6292]: Error reading events from display: Broken pipe
Nov 14 23:20:49 coffee org.gnome.Shell.desktop[6113]: could not connect to wayland server
Nov 14 23:20:49 coffee org.gnome.Shell.desktop[6113]: (EE)
Nov 14 23:20:49 coffee org.gnome.Shell.desktop[6113]: Fatal server error:
Nov 14 23:20:49 coffee org.gnome.Shell.desktop[6113]: (EE) Couldn't add screen
Nov 14 23:20:49 coffee org.gnome.Shell.desktop[6113]: (EE)
```

The install script changes this `MediaKeys` variable:

```
    media_keys=org.gnome.settings-daemon.plugins.media-keys
    custom_kbd=org.gnome.settings-daemon.plugins.media-keys.custom-keybindings
    kbd_path=/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/vim-anywhere
    gsettings set $media_keys custom-keybindings "['others', '$kbd_path']"
    gsettings set $custom_kbd:$kbd_path name $name
    gsettings set $custom_kbd:$kbd_path binding $binding
    gsettings set $custom_kbd:$kbd_path command $action
``` 

I fixed my issue with the following:

```
media_keys=org.gnome.settings-daemon.plugins.media-keys
gsettings reset $media_keys custom-keybindings
```

So I was unable to test out `vim-anywhere`. I would love to try again at some point, it looks great! :smile: 
I would love to know if the bug is reproducible by others.

**Comment by base0x10** [comment]
This error is reproducible on fedora 27, and the fix @basile-henry mentioned works.  

I don't have a lot to add, I don't know gnome well enough to debug.

**Comment by cristobaltapia** [comment]
This also happened to me using Gnome-Shell in Arch Linux. The fix works.

**Comment by pacuna** [comment]
@basile-henry thanks, I though I was going to have to re-install Linux on my laptop (Fedora 27)

**Comment by akkartik** [comment]
I had *weird* issues with Ubuntu 16.04 as well. My system fonts started acting up, oscillating between two sizes twice per second or so. All my custom keybindings broke. I couldn't create any new keybindings that worked. Even after running the `uninstall` script. @basile-henry's command fixed everything, though, and the angels sang in the sky.

I still had to recreate my old custom keybindings. But I'll take that. A million thanks!
