### ISSUE TITLE
Support for emacs-anywhere

### ISSUE THREAD

**Issue by ryukinix** [cknadler/vim-anywhere#66]

**Comment by cknadler** [comment]
Haha, great suggestion! I probably wont ever implement this, but you're welcome to send a PR if you're interested.

I generally want everything in vim-anywhere to be cross platform (OSX & Linux), just as a heads up.

**Comment by mistahchris** [comment]
[72](https://github.com/cknadler/vim-anywhere/pull/72) can do this.
just add one of the following to your `$HOME/.profile`

`VISUAL=/usr/local/bin/emacs`
or
`VISUAL="/usr/local/bin/emacsclient -c"`

**Comment by ryukinix** [comment]
@mistahchris awesome!

**Comment by diego-alvarez-hs** [comment]
up!

**Comment by ryukinix** [comment]
https://github.com/zachcurry/emacs-anywhere closed since someone already supported the idea. Thanks.
