### ISSUE TITLE
The content I input in vim-anywhere didn't copy to input text at Linux Mint

### ISSUE THREAD

**Issue by grants** [cknadler/vim-anywhere#79]
The content I input in vim-anywhere didn't copy to input text at Linux Mint.

**Comment by JSybrandt** [comment]
Ditto, Ubuntu 17.10

**Comment by cknadler** [comment]
Hey,

Sorry you're having issues on Linux. Can you share a few more details on the behavior you're seeing? Are you closing vim-anywhere with `:wq`? The text should end up in your clipboard. What happens when you type `ctrl+v`?

**Comment by JSybrandt** [comment]
I just checked on ubuntu 17.10 and it copied but didn't paste.
So I can type "crtl+v" to paste it manually.

**Comment by cknadler** [comment]
Yep, this is by design. There are pull requests open to automatically paste, but none have been merged yet. 

```
Once invoked, vim-anywhere will open a buffer. Close it and its contents are copied to your clipboard and your previous application is refocused.
```

Resolving as by design. Feel free to reopen if there is anything else I can help with.
