### ISSUE TITLE
Support for neovim

### ISSUE THREAD

**Issue by letientai299** [cknadler/vim-anywhere#86]
There's [nvim-wrapper](https://github.com/fmoralesc/neovim-gnome-terminal-wrapper). Recent version of neovim for Ubuntu also come with a terminal wrapper by themeself (I'm not sure if they're using nvim-wrapper directly or not). 

So, I believe we could replace gvim by nvim for neovim user. How do you think?

**Comment by butlerx** [comment]
if this could be configured to a specific binary it'd be better. as I use urxvt, so i modified the script to run `urxvt -e nvim`

**Comment by letientai299** [comment]
How about define a ENV variable which take default value as what we currently have for 3 systems, user can then override that variable with whatever they want?

**Comment by letientai299** [comment]
I'm closing this since this is nearly a duplication with #73, and also the idea that allow custom editor is mention in [this comment](https://github.com/cknadler/vim-anywhere/issues/73#issuecomment-368326764).
