### ISSUE TITLE
not working? (with screencast)

### ISSUE THREAD

**Issue by seguri** [cknadler/vim-anywhere#92]
I think I did the same steps as in your README but no text appeared:

https://youtu.be/I9L6DABWp34

**Comment by jonsmithers** [comment]
Have you seen the [FAQ](https://github.com/cknadler/vim-anywhere/blob/master/FAQ.md) already?

**Comment by seguri** [comment]
No, thanks. I think this shouldn't be a FAQ but something very clear in the README. I'll send a PR
